### ISSUE TITLE
Tesseract_fast trained data cannot be used in .NET wrapper Tesseract4.0 engine 

### ISSUE THREAD

**Issue by MerlinArul** [tesseract-ocr/tessdata_fast#15]
I am using tesseract 4.0 .net wrapper dll and tying to use tesseract_fast trained data, but it is not gettng instialized and it throws an unhandled exception (read write) . I tried with engine mode "Lstmonly" and "default" but couldn't intialize. Kindly help me whether i am using in a wrong way or i should not used this fast traineddata. 
Error is as follows
![image](https://user-images.githubusercontent.com/28805589/38933426-870f345e-4336-11e8-9eb7-5e458a8f928b.png)

**Comment by zdenop** [comment]
We do not provide support for 3rd party project unless you are able to reproduce error with tesseract executable,
