### ISSUE TITLE
Update description for repo - Suggested Text:

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tessdata_fast#25]
Fast (integer version) trained LSTM models

**Comment by stweil** [comment]
There is already a description: "Fast integer versions of trained models".
Do you suggest to change it?

**Comment by Shreeshrii** [comment]
You can phrase it differently for clarity. Basically I would like it to convey that these don't include legacy models, will work only with --oem 1. Similarly for tessdata_best.

tessdata can convey that it supports both legacy and lstm.

**Comment by stweil** [comment]
I added "LSTM" now, similar to the description for tessdata_best.

**Comment by Shreeshrii** [comment]
Thanks.
