### ISSUE TITLE
Create a new tessdata_fast release/tag?

### ISSUE THREAD

**Issue by MerlijnWajer** [tesseract-ocr/tessdata_fast#26]
As emailed to the mailing list, does it make sense to tag another release?

```
> Hi,
>
> With Tesseract now switching to regular (alpha) releases of 5.0.0; does
> it make sense to consider some versioning for language files as well?
>
> The Internet Archive has switched to using Tesseract for all our OCR,
> and I'm hoping that we can record exactly what version of language files
> was used for a specific OCR job. Currently, the answer is simple, since
> we're using the default packages from Ubuntu focal, but I am working on
> switching to Tesseract release/tag 5.0.0-20201231.
>
> But the tessdata_fast (or tessdata_best, for that matter) do not seem to
> have any recent 5.x releases:
> https://github.com/tesseract-ocr/tessdata_fast/releases
>
> Are there plans to create a release/tag for the tessdata_* repositories?
>
> Cheers,
> Merlijn
```

And the follow-up:

```
On 27/01/2021 12:42, Shree Devi Kumar wrote:
>> The Internet Archive has switched to using Tesseract for all our OCR,
> 
> I am so happy to hear this. It will be great to have the Indic languages
> that were marked as non-ocrable so far be converted to text correctly on
> Internet Archive.
> 
> Is there any page with instructions to do this? Can a language be specified
> while OCRing? eg. Better results are many times received using
> script/Devanagari instead of san for Sanskrit.
> 
> Regarding your question about tessdata, there have only been minor changes
> to tessdata files but adding a tag is a good idea. I suggest you post this
> as a feature request in the repo.
```

**Comment by Shreeshrii** [comment]
@stweil @zdenop @amitdo 
I think it is a good idea to add versioning for language files. 
Should we tag them every time the main repo is tagged?

**Comment by stweil** [comment]
I would not do that because I find it confusing to have several tags for the same revision. Therefore I suggest adding a `4.1.0` tag / release and can do that if there are no other suggestions.

**Comment by amitdo** [comment]
>Releases 3
>Version 4.0 release Latest
>on Oct 30, 2018

>Version 4.0 release
>Latest release
>
>4.0.0
>b893ed3
>
>@zdenop zdenop released this on Oct 30, 2018 · 7 commits to master since this release
>
>trainneddata files for 4.0 release

This is also confusing.

I suggest to add a comment to the README that make it clear that 4.0/4.1 tags and the latest commit are compatible with tesseract 5.0.

**Comment by Shreeshrii** [comment]
Would tessdata and tessdata_best also be tagged?

Should the version string in the files be updated to reflect the tag?

@stweil Are you planning to provide the improved Fraktur traineddata as part of these repos or tessdata_contrib?

**Comment by stweil** [comment]
> This is also confusing.

I updated the release comment for the 4.0.0 tag, so it is now hopefully clearer.

**Comment by stweil** [comment]
> Would tessdata and tessdata_best also be tagged?

They currently have the same tags as `tessdata_fast`. Would that be useful for the future, too?

> Should the version string in the files be updated to reflect the tag?

No, I don't think so. The tag should reflect the Tesseract release which was used for training.

> Are you planning to provide the improved Fraktur traineddata as part of these repos or tessdata_contrib?

Which one of them? I try currently to train new ones based on improved ground truth.

**Comment by Shreeshrii** [comment]
>I suggest adding a 4.1.0 tag / release and can do that if there are no other suggestions.

@stweil You can go ahead and do so for all three tessdata repos.

Regarding Fraktur, I can add a link to your training page from the documentation.

**Comment by Shreeshrii** [comment]
Continuing [discussion in Google group mailing list](https://groups.google.com/g/tesseract-ocr/c/y_78hD8eIw4/m/yRBxSp1GAwAJ)

**Comment by stweil** [comment]
There is now a 4.1.0 release available for tessdata_fast, tessdata and tessdata_best.

**Comment by stweil** [comment]
@MerlijnWajer, can we close this issue?

**Comment by MerlijnWajer** [comment]
Yes, sounds good. (Unrelated, but I did notice that the ubuntu ppa sets TESSDATA_PREFIX to `/usr/share/tesseract-ocr/5`, so providing some advice on what should be used when packaging Tesseract 5 might be helpful)
