### ISSUE TITLE
How to package tessconfigs?

### ISSUE THREAD

**Issue by manisandro** [tesseract-ocr/tessdata_fast#27]
I maintain the Fedora tesseract-tessdata package. I'm unsure how to deal with the tessconfigs folder when packaging. The release archive [1] contains the empty submodule folder, and some broken symlinks which point to files inside the submodule. Is it safe to just ignore the folder and these files? Is there any worth pulling the tessconfigs folder separately and packaging it?

[1] https://github.com/tesseract-ocr/tessdata_fast/archive/4.1.0/tessdata_fast-4.1.0.tar.gz

**Comment by stweil** [comment]
Just ignore that folder. `make install` for tesseract already creates and fills a `tessdata/tessconfigs` folder (like it always did), so that is part of the tesseract package.

**Comment by manisandro** [comment]
Okay, thanks!
