### ISSUE TITLE
Are models compatible with Tesseract 5?

### ISSUE THREAD

**Issue by equal-l2** [tesseract-ocr/tessdata_fast#29]
I'm asking this to clarify, as README was last modified before the 5.0.0 release.

**Comment by stweil** [comment]
Yes, they are compatible. The README should be updated. Do you want to provide a pull request?

**Comment by Doomsdayrs** [comment]
Bump for someone to update the README (or me later)

**Comment by stweil** [comment]
Thanks for the reminder. I added Tesseract 5 now to README.md and close this issue.
