### ISSUE TITLE
Trained data doesn't seem to be working

### ISSUE THREAD

**Issue by AtomR** [tesseract-ocr/tessdata_fast#31]
I downloaded por.traineddata (for portuguese language) to the StreamingAssets/tessdata folder and I get a "TessAPIInit failed. Output: -1".  Should this be enough? I notice there are a bunch of different files for starting with eng  like "eng.cube.params", "eng.cube.nn" and so many others? Should there be the same for portuguese?

**Comment by stweil** [comment]
Typically this error occurs when users did not use the correct link to download a traineddata file. Please open your `por.traineddata` in a text editor. Does it look like HTML code? Then you got the wrong link.

**Comment by stweil** [comment]
> "eng.cube.params", "eng.cube.nn" and so many others

Where did you see such files? They are not in our official repositories and no longer valid for Tesseract 4 and 5.

**Comment by zdenop** [comment]
> StreamingAssets/tessdata

@stweil: seems like he is trying to upgrade the 3rd party app. IMO not a Tesseract issue...
