### ISSUE TITLE
Is tessdata-fast compatible with Linux platform?

### ISSUE THREAD

**Issue by sk02v** [tesseract-ocr/tessdata_fast#33]
I am facing an issue with tessdata-fast in Linux machine. I have checked in Linux docket container and Linux ubuntu virtual machine.
How to resolve this issue?

**Comment by stweil** [comment]
Sure, it is compatible with all platforms.
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.
