### ISSUE TITLE
equ.traineddata is not included

### ISSUE THREAD

**Issue by TerryZH** [tesseract-ocr/tessdata_fast#4]
According to the wiki, equ and osd trained data will reuse the 3.x data file. The weird thing is that osd is copied but equ is not. Is there any reason? e.g. equ is deprecated in 4.x

**Comment by amitdo** [comment]
For --oem 0 it should still work. 
https://github.com/tesseract-ocr/tesseract/blob/2cc531e6bf0288fc8a9ad1c123a252395f00bf56/ccmain/tesseractclass.cpp#L489
You need to set it to 1 / true.

For --oem 1, I'm not sure.

**Comment by ramikalai** [comment]
What is the status of this issue? I would also like to use the equ language option which doesn't seem to be included.

**Comment by stweil** [comment]
Of course it's always possible to get `equ.traineddata` from https://github.com/tesseract-ocr/tessdata.

@amitdo, @Shreeshrii, @zdenop, what do you think? Should we duplicate the file in `tessdata_fast` and `tessdata_best`? @AlexanderP, I just saw that it is also missing in the Debian distribution.

**Comment by Shreeshrii** [comment]
@stweil is there a test case to check that equ.traineddata gives the desired results before duplicating it.

**Comment by stweil** [comment]
[equationdetect_test](https://github.com/tesseract-ocr/tesseract/blob/master/unittest/equationdetect_test.cc) should test it. It requires `equ.traineddata`.

**Comment by stweil** [comment]
I just created two pull requests https://github.com/AlexanderP/tesseract-debian/pull/5 and https://github.com/AlexanderP/tesseract-lang-debian/pull/3 to add the missing package to Debian.

**Comment by stweil** [comment]
Does anybody know how `equ.traineddata` was created? Maybe @jbreiden? `equ` is missing in https://github.com/tesseract-ocr/langdata. And `osd` is missing there, too.

**Comment by amitdo** [comment]
For osd, see this paper:
https://ai.google/research/pubs/pub35506

You can unpack the traineddata to see the unicharset.

**Comment by stweil** [comment]
> Should we duplicate the file in tessdata_fast and tessdata_best?

Was there an answer now? If nobody objects, I'll add `equ.traineddata` to both repositories by the end of the week.

**Comment by stweil** [comment]
Commit 65727574dfcd264acbb0c3e07860e4e9e9b22185 added the file, so this issue can be closed.

**Comment by jbreiden** [comment]
I just noticed this issue. The equation recognizer was left out
deliberately from Tesseract 4.
The Tesseract 3 version works very poorly. And it was not easy to create a
new one for
Tesseract 4. So Ray decided to abandon it.

Maybe one day it will be possible to remove all Tesseract 3 code and data.
(This is hard
and maybe impossible because OSD is so critical) But I think that that
holding onto the
old equation recognizer is not worth it.

**Comment by Shreeshrii** [comment]
@stweil In light of above, Commit 6572757  will need to be reverted.

@AlexanderP https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr/+packages?field.name_filter=equ&field.status_filter=published&field.series_filter= packages are not needed.

**Comment by stweil** [comment]
I think that we should still keep equ.traineddata as even the latest Tesseract claims to be compatible with Tesseract 3. Maybe it was useful for some users in special applications. equ.traineddata is a rather small file, so it does not harm when it is installed but never used.

**Comment by jbreiden** [comment]
The main danger is angry users. People wondering why the equation
recognizer performs so badly, and especially users getting mad if it
disappears out from under them in the future. I'm tempted to let the GitHub
users (who are more advanced) do whatever they want, but maybe not
distribute the equation recognizer through Debian & other Linux
distributions. Does that sound reasonable?

**Comment by amitdo** [comment]
Here is the paper describing the equation detection algorithm:
[A Simple Equation Region Detector for Printed Document Images in Tesseract](https://www.researchgate.net/publication/261199419_A_Simple_Equation_Region_Detector_for_Printed_Document_Images_in_Tesseract)

**Comment by amitdo** [comment]
@stweil,

You added equ.traineddata to the fast repo but not to the best repo.

https://github.com/tesseract-ocr/tessdata_fast/commit/65727574dfcd264acbb0c3e07860e4e9e9b22185

**Comment by stweil** [comment]
Right, thanks. That's fixed now in commit https://github.com/tesseract-ocr/tessdata_best/commit/fa8481f199a7c28dc8fd9633be7158b8d029b801.
