### ISSUE TITLE
osd.traineddata leads core dump when psm =0

### ISSUE THREAD

**Issue by pczzy** [tesseract-ocr/tessdata_fast#5]
super@super-lap:/home/tesseract-lstm$ bin/tesseract --psm 0 ./tessinput.tif stdout
Page 1
Segmentation fault (core dumped)

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/issues/1167

**Comment by amitdo** [comment]
@zdenop, please close this issue.
